# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'google-api-client'

# ref https://stackoverflow.com/questions/5720484/how-to-solve-certificate-verify-failed-on-windows
gem 'certified'
